source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'jekyll'
  gem 'jekyll-feed'
  gem 'jekyll-sitemap'
  gem 'jekyll-redirect-from'
  gem 'jemoji'
  gem 'webrick', '~> 1.8'  # If you need the web server gem for local development
  gem 'csv', '3.3.2'
  gem 'i18n', '1.14.6'
  gem 'nokogiri', '1.18.1'
  gem 'concurrent-ruby', '1.3.4'
  gem 'rexml', '3.4.0'
  gem 'activesupport', '7.2.2.1'
  gem 'dnsruby', '1.72.3'
  gem 'commonmarker', '0.23.11'
  gem 'rubyzip', '2.4.1'
  gem 'mini_portile2', '2.8.8'
  gem 'benchmark', '0.4.0'
  gem 'bigdecimal', '3.1.9'
  gem 'connection_pool', '2.5.0'
  gem 'logger', '1.6.4'
  gem 'minitest', '5.25.4'
  gem 'securerandom', '0.4.1'
  gem 'faraday', '2.12.2'
  gem 'execjs', '2.10.0'
  gem 'ffi', '1.17.0'
  gem 'faraday-net_http', '3.4.0'
  gem 'json', '2.9.1'
  gem 'net-http', '0.6.0'
  gem 'uri', '1.0.2'
end

gem 'github-pages'