name: Build and Deploy AcademicPages to GitHub Pages

on:
  push:
    branches:
      - main   # Adjust if your default branch is different
  workflow_dispatch:   # Allows manual triggering from GitHub Actions UI

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu for your build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Set up Ruby (Jekyll's environment)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # You can use a specific version of Ruby here
          bundler-cache: true  # Cache gems to speed up subsequent builds

      # Install dependencies from the Gemfile (this includes Jekyll and other gems)
      - name: Install dependencies
        run: |
          bundle install  # Installs gems defined in the Gemfile

      # Build the Jekyll site
      - name: Build site with Jekyll
        run: |
          bundle exec jekyll build --destination ./_site --baseurl ""  # Adjust baseurl if needed

      # Upload build output as an artifact for deployment
      - name: Upload site artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site  # Path to the build output directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
