name: Deploy Jekyll AcademicPages #trigger depl

on:
  push:
    branches:
      - main  # Change 'main' to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Ruby environment
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1  # Specify a compatible Ruby version
        bundler-cache: true

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        bundle install

    # Step 4: Build the site
    - name: Build site
      run: |
        bundle exec jekyll build

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
